//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tools.SerializableStringDictionary VeloBankAcountNumbers {
            get {
                return ((global::Tools.SerializableStringDictionary)(this["VeloBankAcountNumbers"]));
            }
            set {
                this["VeloBankAcountNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0001-01-02")]
        public global::System.DateTime VeloBankAcountNumbersDownloadDate {
            get {
                return ((global::System.DateTime)(this["VeloBankAcountNumbersDownloadDate"]));
            }
            set {
                this["VeloBankAcountNumbersDownloadDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Tools.SerializableStringDictionary GetinBankAcountNumbers {
            get {
                return ((global::Tools.SerializableStringDictionary)(this["GetinBankAcountNumbers"]));
            }
            set {
                this["GetinBankAcountNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0001-01-02")]
        public global::System.DateTime GetinBankAcountNumbersDownloadDate {
            get {
                return ((global::System.DateTime)(this["GetinBankAcountNumbersDownloadDate"]));
            }
            set {
                this["GetinBankAcountNumbersDownloadDate"] = value;
            }
        }
    }
}
